if __name__ == "__main__":
    print("Hello, world!")
    print("This script tests the bot's ability to generate a commit message from a diff.")
    print("The diff is generated by comparing the current state of the repo to the previous commit.")
