name: Update AI Changelog on Push to Main

on:
  push:
    branches: [main]
    paths-ignore:
      - "AI_CHANGELOG.md"

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip

    - name: Install Python libraries
      run: |
        pip install --user -r requirements.txt
        pip install --user .

    - name: "gpt-4: AI_CHANGELOG.md"
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
        LANGCHAIN_PROJECT: ai-changelog
        LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
        LANGCHAIN_TRACING_V2: true
      run: |
        ai_changelog origin/main^..origin/main \
        --provider openai \
        --model gpt-4 \
        -o AI_CHANGELOG.md

    - name: "claude-2: AI_CHANGELOG-claude-2.md"
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
        LANGCHAIN_PROJECT: ai-changelog
        LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
        LANGCHAIN_TRACING_V2: true
      run: |
        ai_changelog origin/main^..origin/main \
          --provider anthropic \
          --model claude-2 \
          --max_concurrency 5 \
          --temperature 0 \
          -o AI_CHANGELOG-claude-2.md

#    - name: "codellama: AI_CHANGELOG-codellama.md"
#      env:
#        ANYSCALE_API_KEY: ${{ secrets.ANYSCALE_API_KEY }}
#        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
#        LANGCHAIN_PROJECT: ai-changelog
#        LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
#        LANGCHAIN_TRACING_V2: true
#      run: |
#        ai_changelog origin/main^..origin/main \
#          --provider anyscale \
#          --model "codellama/CodeLlama-34b-Instruct-hf" \
#          --temperature 0 \
#          -o AI_CHANGELOG-codellama.md

    - name: Commit changes
      with:
        COMMIT_MESSAGE: "Update AI Changelog"
        file_pattern: "AI_CHANGELOG.md"
      uses: stefanzweifel/git-auto-commit-action@v4
