name: Push to Docker Hub

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-push-docker:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: joshuasundance
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build \
          -t joshuasundance/ai_changelog:${{ github.ref_name }} \
          -t joshuasundance/ai_changelog:latest \
          .

    - name: Push to Docker Hub
      run: docker push -a joshuasundance/ai_changelog
